[book]
authors = ["Jeremy HERGAULT <jeremy.hergault@worldline.com>", "Anthony THOMAS <anthony.thomas@worldline.com>", "Olivier SCHYNS <olivier.schyns@worldline.com>", "Rene-Louis EYMARD <rene-louis.eymard@worldline.com>"]
title = "ProSA - Protocol Service Adaptor"
src = "src"
language = "en"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-css = ["worldline.css"]
git-repository-url = "https://github.com/worldline/ProSA"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
